[package]
name = "oofer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "1.6.2"
rand = "0.8.5"
walkdir = "2.4.0"
